#spring.application.name=SpringAOP
#
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring:
  application:
    name: SpringAOP
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
